name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - name: Install GitVersion
      uses: gittools/actions/gitversion/execute@v0
      id: gitversion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Clean Build Output
      run: dotnet clean EFCore.MockBuilder/EFCore.MockBuilder.csproj --configuration Release

    - name: Restore dependencies
      run: dotnet restore EFCore.MockBuilder/EFCore.MockBuilder.csproj

    - name: Build
      run: dotnet build EFCore.MockBuilder/EFCore.MockBuilder.csproj --configuration Release /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Pack NuGet Package
      run: dotnet pack EFCore.MockBuilder/EFCore.MockBuilder.csproj --configuration Release /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: List Packed Files
      run: ls EFCore.MockBuilder/bin/Release/

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push EFCore.MockBuilder/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
